### ISSUE TITLE
CRI-O port whole crio.conf

### ISSUE THREAD

**Issue by gildub** [konveyor/cpma#427]
OCP 4 Machine Configuration Operator (MCO) supports injection of configuration file as URL data [1].
This would be an alternative to using CR options which are limited to 3 options at the moment.
Being able to port the entire crio.conf seems to be more adapted from a migration perspective.
The trade off is to leave any backward compatiblity issue with CRI-O configuration to the user as we can't validate those.

[1] https://github.com/openshift/machine-config-operator#applying-configuration-changes-to-the-cluster

**Comment by jmontleon** [comment]
I have been told by an MCO developer this is not the desired approach. And it's probably unsupported.

**Comment by gildub** [comment]
Passing a file to MCO is supported:
https://github.com/openshift/machine-config-operator#applying-configuration-changes-to-the-cluster

The fields handled by MCO are the ones likely to be changed by user and considered as such by MCO. I wonder if some customers have other modified parameters in the source OCP and would like to port them?

**Comment by gildub** [comment]
Closing as this approach is not going to be supported.
